name: Merge requests CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  FRONTEND_DIR: view.react

jobs:
  test:
    name: Run all tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12, 18 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test with gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test

    - name: Setup Node.js env
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install
      working-directory: ${{ env.FRONTEND_DIR }}

    - name: npm run build
      run: npm run build --if-present
      working-directory: ${{ env.FRONTEND_DIR }}

    - name: run frontend tests
      run: npm test
      working-directory: ${{ env.FRONTEND_DIR }}

  check-linters:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        working-directory: ${{ env.FRONTEND_DIR }}
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
        working-directory: ${{ env.FRONTEND_DIR }}
      - run: npm run lint
        working-directory: ${{ env.FRONTEND_DIR }}
